create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
create table account (employeenumber integer not null, id varchar(255) not null, location varchar(255), name varchar(255) unique, password varchar(255), role varchar(255) check (role in ('ROLE_ADMIN','ROLE_USER')), primary key (id));
create table customer (customernumber integer not null, address varchar(255), email varchar(255), id varchar(255) not null, name varchar(255), phonenumber varchar(255), preferred_package varchar(255), primary key (id));
create table location (address varchar(255), id varchar(255) not null, stock varchar(255) unique, primary key (id));
create table log (dateoflog date, packagingamount integer not null, timeoflog timestamp(9), account varchar(255), id varchar(255) not null, packaging varchar(255) unique, product varchar(255) unique, primary key (id));
create table orders (ordernumber integer not null, customer varchar(255), id varchar(255) not null, name varchar(255), primary key (id));
create table packaging (amountinstock integer not null, minamount integer not null, id varchar(255) not null, name varchar(255), packaginggroup varchar(255), stock varchar(255), primary key (id));
create table product (ispacked boolean, productnumber integer not null, producttype smallint check (producttype between 0 and 1), id varchar(255) not null, name varchar(255), order_ varchar(255), prefferedpackage varchar(255), primary key (id));
create table stock (stocknumber integer not null, id varchar(255) not null, primary key (id));
alter table if exists account add constraint FK2tpaww1kt5adx3u9v3wqh3k28 foreign key (location) references location;
alter table if exists customer add constraint FKhesahr8ujmil47u3qhewxl1rf foreign key (preferred_package) references packaging;
alter table if exists location add constraint FKr69vwyxvfshye6ys4hmpo82xf foreign key (stock) references stock;
alter table if exists log add constraint FKrg0ts8gmr5ndx59a4eqcq493g foreign key (account) references account;
alter table if exists log add constraint FK9k9q58bt400kn4rbinp7gb9pe foreign key (packaging) references packaging;
alter table if exists log add constraint FKiyxyroolnsitaajnd0u6w3hnb foreign key (product) references product;
alter table if exists orders add constraint FKp1mlwxe5nhua51hv0fo39ywbw foreign key (customer) references customer;
alter table if exists packaging add constraint FKntc32h6hkdxbu3yeu716q1b1w foreign key (stock) references stock;
alter table if exists product add constraint FKs3p8ij095x4wm5k196t0523xe foreign key (order_) references orders;
alter table if exists product add constraint FKixc4ja3e2avcm87xnayj1mstx foreign key (prefferedpackage) references packaging;
