version: '3.1'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=db_name
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_password
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=email
      - MAIL_PASSWORD=password
      - JWT_SECRET=secret
    networks:
      - backend
      - external

networks:
  backend:
    driver: bridge
    internal: true
  external:

volumes:
  postgres-data:
